### ISSUE TITLE
Old version of MariaDB

### ISSUE THREAD

**Issue by sjmcdowall** [arizonatribe/centosmariadb#1]
I think we'd like to start using the latest (sort of) production MariaDB which is 10.1.XX .. looks like you grabbed the 5.6X flavor of MySQL .. Can we update the image to have the 10.1 line ??

**Comment by arizonatribe** [comment]
Version 5.6 is the default version when you do a `yum install mariadb-server`. To install a different version in this type of environment would just mean creating a `/etc/yum.repos.d/Maria.repo` pointing to something like http://yum.mariadb.org/10.1/centos7-amd64 and then `yum install -y Maria`.
